version: '3'
services:
  database:
    image: 'mongo'
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=tessmann
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=root
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database:/data/db 
    ports:
      - 27017:27017